/**
 * @fileoverview ExecutionKernel interface definitions.
 * @description Defines the core execution engine interface for Record-Replay V3.
 */

import type { JsonObject } from '../../domain/json';
import type { FlowId, NodeId, RunId } from '../../domain/ids';
import type { RRError } from '../../domain/errors';
import type { FlowV3 } from '../../domain/flow';
import type { DebuggerCommand, DebuggerState } from '../../domain/debug';
import type { RunEvent, RunStatus, Unsubscribe } from '../../domain/events';

/**
 * Run start request.
 */
export interface RunStartRequest {
  /** Run ID generated by the caller. */
  runId: RunId;
  /** Flow ID */
  flowId: FlowId;
  /** Flow snapshot used during execution. */
  flowSnapshot: FlowV3;
  /** Run arguments. */
  args?: JsonObject;
  /** Start node ID, defaulting to Flow.entryNodeId. */
  startNodeId?: NodeId;
  /** Tab ID allocated by the caller, exclusive to this run. */
  tabId: number;
  /** Debug configuration. */
  debug?: { breakpoints?: NodeId[]; pauseOnStart?: boolean };
}

/**
 * Run execution result.
 */
export interface RunResult {
  /** Run ID */
  runId: RunId;
  /** Final status. */
  status: Extract<RunStatus, 'succeeded' | 'failed' | 'canceled'>;
  /** Total duration in milliseconds. */
  tookMs: number;
  /** Error details if the run failed. */
  error?: RRError;
  /** Output values. */
  outputs?: JsonObject;
}

/**
 * Run status query result.
 */
export interface RunStatusInfo {
  /** Current status. */
  status: RunStatus;
  /** Current node ID. */
  currentNodeId?: NodeId;
  /** Start time. */
  startedAt?: number;
  /** Last updated time. */
  updatedAt: number;
  /** Tab ID */
  tabId?: number;
}

/**
 * ExecutionKernel interface.
 * @description Core execution engine for Record-Replay V3.
 */
export interface ExecutionKernel {
  /**
   * Subscribe to the event stream.
   * @param listener Event listener.
   * @returns Unsubscribe function.
   */
  onEvent(listener: (event: RunEvent) => void): Unsubscribe;

  /**
   * Start a run.
   * @description Queues the run and begins execution.
   */
  startRun(req: RunStartRequest): Promise<void>;

  /**
   * Pause a run.
   * @param runId Run ID.
   * @param reason Pause reason.
   */
  pauseRun(runId: RunId, reason?: { kind: 'command' }): Promise<void>;

  /**
   * Resume a run.
   * @param runId Run ID.
   */
  resumeRun(runId: RunId): Promise<void>;

  /**
   * Cancel a run.
   * @param runId Run ID.
   * @param reason Cancel reason.
   */
  cancelRun(runId: RunId, reason?: string): Promise<void>;

  /**
   * Execute a debug command.
   * @param runId Run ID.
   * @param cmd Debug command.
   */
  debug(
    runId: RunId,
    cmd: DebuggerCommand,
  ): Promise<{ ok: true; state?: DebuggerState } | { ok: false; error: string }>;

  /**
   * Get run status.
   * @param runId Run ID.
   * @returns Run status info, or null if it does not exist.
   */
  getRunStatus(runId: RunId): Promise<RunStatusInfo | null>;

  /**
   * Recover execution.
   * @description Called after a service worker restart to recover interrupted runs.
   */
  recover(): Promise<void>;
}

/**
 * Create a not-yet-implemented ExecutionKernel.
 * @description Phase 0 placeholder implementation.
 */
export function createNotImplementedKernel(): ExecutionKernel {
  const notImplemented = () => {
    throw new Error('ExecutionKernel not implemented');
  };

  return {
    onEvent: () => {
      notImplemented();
      return () => {};
    },
    startRun: async () => notImplemented(),
    pauseRun: async () => notImplemented(),
    resumeRun: async () => notImplemented(),
    cancelRun: async () => notImplemented(),
    debug: async () => notImplemented(),
    getRunStatus: async () => notImplemented(),
    recover: async () => notImplemented(),
  };
}
